name = "writeguardapp"
compatibility_date = "2024-01-01"

[site]
bucket = "./out"

[[build]]
command = "npm run build"
upload.format = "directory"
upload.path = "./out"

[env.production]
name = "writeguardapp"

[env.preview]
name = "writeguardapp-preview"