name: Deploy to HF Spaces

on:
  push:
    paths:
      - 'huggingface/**'
    branches:
      - main  # Only deploy from main branch, not PRs
  workflow_dispatch:  # Manual trigger

concurrency:
  group: deploy-hf-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to HF Spaces
      uses: huggingface/huggingface_hub@main
      with:
        hf_token: ${{ secrets.HF_TOKEN }}
        repo_id: YOUR_USERNAME/text-compare
        repo_type: space
        source_dir: ./huggingface
    
    - name: Deployment complete
      run: echo "✅ Deployed to HF Spaces successfully"